#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.

HOURS=0
MINUTES=1
while [ $HOURS -le 12 ];
do
    echo "Hour: $HOURS"
    while [ $MINUTES -lt 60 ];
    do
        echo "$MINUTES"
	((MINUTES++))
    done
    MINUTES=1
    ((HOURS++))
    
done
